SPEC: ldt_internal_external.csv
COEFFICIENTS: ldt_internal_external_coefficients.csv
COEFFICIENT_TEMPLATE: ldt_internal_external_coefficient_template.csv

LOGIT_TYPE: MNL

CONSTANTS:
  DUMMY_CONSTANT: 1

CATEGORY_CONSTANTS: categories.yaml
