SPEC: ldt_external_mode_choice.csv

LOGIT_TYPE: NL

NESTS: 
  name: root
  coefficient: 1.0
  alternatives:
    - DRIVE
    - AIR
    - name: TRANSIT
      coefficient: 0.65
      alternatives:
      - WALK_TRANSIT
      - DRIVE_TRANSIT

SPEC_CATEGORIES: 
  - NAME: HOUSEHOLD
    COEFFICIENTS: ldt_external_mode_choice_household_coefficients.csv
  - NAME: WORKRELATED
    COEFFICIENTS: ldt_external_mode_choice_workrelated_coefficients.csv
  - NAME: OTHER
    COEFFICIENTS: ldt_external_mode_choice_other_coefficients.csv

CONSTANTS:
  DUMMY_CONSTANT: 1