SAMPLE_SPEC: ldt_internal_tour_destination_sample.csv
SPEC: ldt_internal_tour_destination.csv
COEFFICIENTS: ldt_internal_tour_destination_coefficients.csv

SAMPLE_SIZE: 30

SIZE_TERM_SELECTOR: ldt

# we can't use use household income_segment as this will also be set for non-workers
CHOOSER_SEGMENT_COLUMN_NAME: ldt_tour_segment

# optional (comment out if not desired)
DEST_CHOICE_LOGSUM_COLUMN_NAME: destination_logsum

# comment out DEST_CHOICE_LOGSUM_COLUMN_NAME if saved alt logsum table
DEST_CHOICE_SAMPLE_TABLE_NAME: tour_destination_sample


SEGMENTS:
  # household tours are sub-segmented only by daytrip / overnight
  - [household_day, household]
  - [household_overnight, household]
  # individual work related tours are sub-segmented by daytrip / overnight and worker industry category
  - [workrelated_day_1, person_workrelated]
  - [workrelated_day_2, person_workrelated]
  - [workrelated_day_3, person_workrelated]
  - [workrelated_day_4, person_workrelated]
  - [workrelated_day_5, person_workrelated]
  - [workrelated_day_6, person_workrelated]
  - [workrelated_day_7, person_workrelated]
  - [workrelated_day_8, person_workrelated]
  - [workrelated_day_9, person_workrelated]
  - [workrelated_day_10, person_workrelated]
  - [workrelated_day_11, person_workrelated]
  - [workrelated_day_12, person_workrelated]
  - [workrelated_day_13, person_workrelated]
  - [workrelated_day_14, person_workrelated]
  - [workrelated_day_15, person_workrelated]
  - [workrelated_day_16, person_workrelated]
  - [workrelated_day_17, person_workrelated]
  - [workrelated_overnight_1, person_workrelated]
  - [workrelated_overnight_2, person_workrelated]
  - [workrelated_overnight_3, person_workrelated]
  - [workrelated_overnight_4, person_workrelated]
  - [workrelated_overnight_5, person_workrelated]
  - [workrelated_overnight_6, person_workrelated]
  - [workrelated_overnight_7, person_workrelated]
  - [workrelated_overnight_8, person_workrelated]
  - [workrelated_overnight_9, person_workrelated]
  - [workrelated_overnight_10, person_workrelated]
  - [workrelated_overnight_11, person_workrelated]
  - [workrelated_overnight_12, person_workrelated]
  - [workrelated_overnight_13, person_workrelated]
  - [workrelated_overnight_14, person_workrelated]
  - [workrelated_overnight_15, person_workrelated]
  - [workrelated_overnight_16, person_workrelated]
  - [workrelated_overnight_17, person_workrelated]
  # individual other tours are sub-segmented by daytrip / overnight and student status
  - [other_day_student, person_other]
  - [other_overnight_student, person_other]
  - [other_day_nonstudent, person_other]
  - [other_overnight_nonstudent, person_other]


SIMULATE_CHOOSER_COLUMNS:
  - tour_type
  - home_zone_id
  - person_id

LOGSUM_SETTINGS: ldt_internal_mode_choice.yaml

# model-specific logsum-related settings
CHOOSER_ORIG_COL_NAME: home_zone_id
ALT_DEST_COL_NAME: alt_dest
IN_PERIOD: 14
OUT_PERIOD: 14
