
SPEC: ldt_tour_gen_person.csv

LOGIT_TYPE: MNL

SPEC_PURPOSES:
  - NAME: WORKRELATED
    COEFFICIENTS: ldt_tour_gen_person_coefficients_WORKRELATED.csv
  - NAME: OTHER
    COEFFICIENTS: ldt_tour_gen_person_coefficients_OTHER.csv

# put global constants here
CONSTANTS:
  DUMMY_CONSTANT: 1
  MALE_CATEGORY: 1
  TOO_YOUNG_SCH_CATEGORY: 0  # only applies to people too young to be in school (age 3 or lower)
  NOT_IN_SCHOOL_CATEGORY: 1
  ONE_FAMILY_HOUSE_DETACHED_CATEGORY: 2
  ONE_FAMILY_HOUSE_ATTACHED_CATEGORY: 3
  
preprocessor:
    SPEC: ldt_tour_gen_person_preprocessor
    DF: persons
    TABLES:
        - accessibility
        - households
