# also completely probabilistic; just needs 2 specifications for each purpose
SPEC_PURPOSES:
  - NAME: WORKRELATED
    CONSTANTS:
        COMPLETE: 0.0695
        BEGIN: 0.0472
        END: 0.0336
        AWAY: 0.1126
        # NOTOUR: 0.7371
  - NAME: OTHER
    CONSTANTS:
        COMPLETE: 0.0286
        BEGIN: 0.0211
        END: 0.0171
        AWAY: 0.0543
        # NOTOUR: 0.8788    
        
preprocessor:
    SPEC: ldt_pattern_person_preprocessor
    DF: persons
    TABLES:
        - households