SPEC: ldt_internal_external.csv

LOGIT_TYPE: MNL

SPEC_CATEGORIES:
  - NAME: HOUSEHOLD
    COEFFICIENTS: ldt_internal_external_household_coefficients.csv
  - NAME: WORKRELATED
    COEFFICIENTS: ldt_internal_external_workrelated_coefficients.csv
  - NAME: OTHER
    COEFFICIENTS: ldt_internal_external_other_coefficients.csv

CONSTANTS: 
  DUMMY_CONSTANT: 1

CATEGORY_CONSTANTS: categories.yaml